# Generated by Django 3.2.7 on 2022-03-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='Author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='ebook',
            old_name='Favourite',
            new_name='favourite',
        ),
        migrations.RenameField(
            model_name='ebook',
            old_name='Genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='ebook',
            old_name='Review',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='ebook',
            old_name='Title',
            new_name='title',
        ),
    ]
