# Generated by Django 3.2.7 on 2022-03-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebookapp', '0006_ebook_userss'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='userss',
            new_name='fkUser',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Usertoken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=1000)),
                ('fkUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ebookapp.user')),
            ],
        ),
    ]
